apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-huj0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-huj0
    app.kubernetes.io/part-of: e2e-nodejs
  name: devfile-sample-huj0
  namespace: e2e-demos-mxkq-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-huj0
    weight: null
status: {}
